language: node_js
node_js:
  - "15"

services:
  - docker

script:
  - docker --version
  # Build Feed
  - docker build -t karangajjar/udagram-api-feed ./Project: Refactor Monolith to Microservices and Deploy/udagram-api-feed
  # Build User
  - docker build -t karangajjar/udagram-api-user ./Project: Refactor Monolith to Microservices and Deploy/udagram-api-user
  # Build Frontend
  - docker build -t karangajjar/udagram-frontend ./Project: Refactor Monolith to Microservices and Deploy/udagram-frontend
  # Build Reverse Proxy
  - docker build -t karangajjar/reverseproxy ./Project: Refactor Monolith to Microservices and Deploy/udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image push karangajjar/udagram-api-feed
  - docker image push karangajjar/udagram-api-user
  - docker image push karangajjar/udagram-frontend
  - docker image push karangajjar/reverseproxy
