apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: karangajjar/udagram-api-feed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      restartPolicy: Always


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: backend-feed
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend-feed
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50